version: '3.8'

services:
  db_test:
    image: postgres:12-alpine
    container_name: db_test
    environment:
      POSTGRES_DB: db_test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "db_test", "-U", "user" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - './.docker_pgdata_test:/var/lib/postgresql/data'
    ports:
      - '5444:5432'

  hm_test:
    build:
      context: .
    working_dir: /app
    command: npm run test
    container_name: hm_test
    depends_on:
      db_test:
        condition: service_healthy
    ports:
      - '3050:3050'
    environment:
      PORT: 3050
      DATABASE_PORT: 5432
      DATABASE_HOST: db_test
      DATABASE_NAME: db_test
      DATABASE_USER: user
      DATABASE_ACCESS_KEY: password
      JWT_SECRET: secret_secret
    volumes:
      - ./:/app
